apiVersion: kobblestone.io/v1alpha1
kind: BackupRepo
metadata:
  name: test-repo
  namespace: minecraft
spec:
  type: PersistentVolumeClaim
  persistentVolumeClaim:
    name: test-repo
    size: 10Gi
    storageClassName: longhorn
---
apiVersion: kobblestone.io/v1alpha1
kind: BackupRepo
metadata:
  name: test-repo-s3
  namespace: minecraft
spec:
  type: S3
  s3:
    endpoint: https://abcdefg.eu.r2.cloudflarestorage.com
    bucket: minecraft-backups
    credentialsSecretRef:
      name: test-repo-s3